#!/bin/bash
# Auto-generate session report on CLI exit

REPORT_DIR="$CLAUDE_PROJECT_DIR/docs/sessions"
mkdir -p "$REPORT_DIR"

DATE=$(date +%Y-%m-%d)
TIME=$(date +%H%M)
REPORT="$REPORT_DIR/${DATE}_${TIME}.md"

# Get recent git changes from this session
RECENT_COMMITS=$(git log --oneline --since="6 hours ago" 2>/dev/null | head -20)
CHANGED_FILES=$(git diff --name-only HEAD~5 2>/dev/null | head -30)

cat > "$REPORT" << EOF
# Session Report: $DATE $TIME

## Files Changed This Session
\`\`\`
$CHANGED_FILES
\`\`\`

## Recent Commits
\`\`\`
$RECENT_COMMITS
\`\`\`

## Work Log
$(cat "$CLAUDE_PROJECT_DIR/.claude/work-log.tmp" 2>/dev/null || echo "No tracked changes")

---
*Auto-generated by Claude Code SessionEnd hook*
EOF

# Clear the temporary work log
> "$CLAUDE_PROJECT_DIR/.claude/work-log.tmp"

echo "Session report saved: $REPORT"
