# Depth refinement module for neural depth correction
"""
Neural depth refinement for correcting MediaPipe depth errors.

Key components:
- model.py: PoseAwareDepthRefiner with POF (Part Orientation Fields) and view angle encoding
- dataset.py: AIST++ training data loader with augmentation
- losses.py: Biomechanical loss functions (depth, bone length, symmetry)

Architecture:
- Cross-joint transformer learns which joints inform depth of others
- View angle encoder captures periodic angle patterns (0-360° azimuth)
- Limb orientation predictor uses 2D foreshortening for depth disambiguation

Training data generated by scripts/data/convert_aistpp.py
"""

from .model import (
    PoseAwareDepthRefiner,
    create_model,
    ViewAngleEncoder,
    Pose2DEncoder,
)
from .dataset import AISTPPDepthDataset, create_dataloaders
from .losses import DepthRefinementLoss

__all__ = [
    'PoseAwareDepthRefiner',
    'create_model',
    'ViewAngleEncoder',
    'Pose2DEncoder',
    'AISTPPDepthDataset',
    'create_dataloaders',
    'DepthRefinementLoss',
]
