# Depth refinement module for neural depth correction
"""
Neural depth refinement for correcting MediaPipe depth errors.

Key components:
- model.py: PoseAwareDepthRefiner with view angle encoding and camera prediction
- dataset.py: AIST++ training data loader with augmentation
- losses.py: Biomechanical loss functions (depth, bone length, symmetry)

Architecture:
- Cross-joint transformer learns which joints inform depth of others
- View angle encoder captures periodic angle patterns (0-360° azimuth)
- Camera angle predictor infers viewing angle from pose (for inference)

Training data generated by scripts/convert_aistpp_to_training.py
"""

from .model import (
    PoseAwareDepthRefiner,
    create_model,
    ViewAngleEncoder,
    CameraPositionPredictor,
    Pose2DEncoder,
    compute_angles_from_camera_position,
)
from .dataset import AISTPPDepthDataset, create_dataloaders
from .losses import DepthRefinementLoss

__all__ = [
    'PoseAwareDepthRefiner',
    'create_model',
    'ViewAngleEncoder',
    'CameraPositionPredictor',
    'Pose2DEncoder',
    'compute_angles_from_camera_position',
    'AISTPPDepthDataset',
    'create_dataloaders',
    'DepthRefinementLoss',
]
