# Joint constraint refinement module for neural joint angle correction
"""
Neural joint constraint refinement for learning realistic joint limits from data.

Key components:
- model.py: JointConstraintRefiner with cross-joint attention
- dataset.py: AIST++ joint angle data loader
- losses.py: Angle reconstruction + soft constraint losses

Architecture:
- Cross-joint transformer learns pose context (bent knee -> different hip constraints)
- Per-joint refinement heads predict angle corrections
- Soft constraints learned from data distribution (not hard-coded limits)

Training data generated by scripts/generate_joint_angle_training.py
"""

from .model import (
    JointConstraintRefiner,
    create_model,
)
from .dataset import AISTPPJointDataset, create_dataloaders
from .losses import JointRefinementLoss
from .inference import JointRefiner, load_refiner

__all__ = [
    'JointConstraintRefiner',
    'create_model',
    'AISTPPJointDataset',
    'create_dataloaders',
    'JointRefinementLoss',
    'JointRefiner',
    'load_refiner',
]
