# Joint constraint refinement module for neural joint angle correction
"""
Neural joint constraint refinement for learning realistic joint limits from data.

Key components:
- model.py: JointConstraintRefiner with cross-joint attention (transformer)
- gnn_model.py: GNN-based refiners (GCN, SemGCN, SemGCN-Temporal)
- graph_utils.py: Graph construction for 12 joints
- dataset.py: AIST++ joint angle data loader (with temporal support)
- losses.py: Angle reconstruction + soft constraint losses + sign/temporal losses

Architecture variants:
- Transformer: Cross-joint attention learns pose context
- SemGCN-Temporal: Graph convolution with temporal context + sign prediction

Training data generated by scripts/data/generate_joint_angles.py
"""

from .model import (
    JointConstraintRefiner,
    create_model,
)
from .gnn_model import (
    JointGCNRefiner,
    SemGCNJointRefiner,
    SemGCNTemporalJointRefiner,
    create_gnn_joint_model,
    load_gnn_joint_model,
    TemporalJointRefinerInference,
)
from .graph_utils import (
    NUM_JOINTS,
    JOINT_NAMES,
    build_kinematic_adj,
    build_symmetry_adj,
    build_hierarchy_adj,
    build_all_adjacencies,
    get_combined_adj,
)
from .dataset import AISTPPJointDataset, TemporalJointDataset, create_dataloaders
from .losses import (
    JointRefinementLoss,
    GNNJointRefinementLoss,
    angular_distance,
    angle_sign_loss,
    temporal_smoothness_loss,
    sign_accuracy,
)
from .inference import JointRefiner, load_refiner

__all__ = [
    # Transformer model
    'JointConstraintRefiner',
    'create_model',
    # GNN models
    'JointGCNRefiner',
    'SemGCNJointRefiner',
    'SemGCNTemporalJointRefiner',
    'create_gnn_joint_model',
    'load_gnn_joint_model',
    'TemporalJointRefinerInference',
    # Graph utilities
    'NUM_JOINTS',
    'JOINT_NAMES',
    'build_kinematic_adj',
    'build_symmetry_adj',
    'build_hierarchy_adj',
    'build_all_adjacencies',
    'get_combined_adj',
    # Datasets
    'AISTPPJointDataset',
    'TemporalJointDataset',
    'create_dataloaders',
    # Losses
    'JointRefinementLoss',
    'GNNJointRefinementLoss',
    'angular_distance',
    'angle_sign_loss',
    'temporal_smoothness_loss',
    'sign_accuracy',
    # Inference
    'JointRefiner',
    'load_refiner',
]
